myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from register.views import AddressEditView
from register import views as v
from print4you import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from register.views import UserEditView

urlpatterns = [

    path('', v.homepage_redirect, name='homepage_redirect'),
    path('homepage/', v.homepage, name='homepage'),
    path('about/', v.about, name='about'),
    path('order/', views.order, name='order'),
    path('offer/', views.offer, name='offer'),
    path('app/', include('print4you.urls')),
    path("register/", v.register, name="register"),
    path("edit_profile/", UserEditView.as_view(), name="edit_profile"),
    path('address_redirect/', v.address_redirect),
    path("set_address/", v.add_address, name="set_address"),
    path("edit_address/", AddressEditView.as_view(), name="edit_address"),
    path('admin/', admin.site.urls),
    path("login/", v.login_request, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile", views.profile_view, name="profile"),
    path("accounts/login/", v.login_request, name='login'),
    path("calculator/", views.calculator, name='calculator'),
    path('update_printout/<str:pk>/',
         views.updatePrintout, name="update_printout"),
    path('neworder/<str:pk>/', views.newOrder, name="new_order"),
    path('payment/<str:pk>/', views.payment, name="payment"),
    path('', include("django.contrib.auth.urls")),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path(
        'password/',
        auth_views.PasswordChangeView.as_view(
            template_name='change_password.html',
            success_url='/'
        ),
        name='password'
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/print4you/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal

SIZE_CHOICES = (
    ('10x15', '10x15'),
    ('13x18', '13x18'),
    ('15x21', '15x21'),
    ('20x25', '20x25'),
    ('A4', 'A4'),
    ('A3', 'A3'),
    ('50x60', '50x60'),
    ('100x50', '100x50'),
    ('100x70', '100x70'),
    ('160x60', '160x60'),
    ('140x100', '140x100'),
    ('118 1mb', '118 1mb')
)

PAYMENT_CHOICS = (
    ('przelew', 'Przelew'),
    ('karta', 'Karta kredytowa/debetowa'),
    ('blik', 'BLIK')
)

DELIVERY_CHOICES = (
    ('poczta', 'Przesyłka pocztowa (+6,70zł)'),
    ('kurier', 'Przesyłka kurierska (+10,90zł)'),
    ('paczkomat', 'Odbiór w paczkomacie (+8,99zł)')
)


class Printout(models.Model):
    is_color = models.BooleanField(default=True)
    is_gloss = models.BooleanField(default=True)
    quantity = models.IntegerField(default=1)
    size = models.CharField(
        max_length=7,
        choices=SIZE_CHOICES,
        default='1'
    )
    image_file = models.ImageField(upload_to='user_prints')
    price = models.DecimalField(max_digits=9, decimal_places=2, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.price == -1:
            if self.size == '10x15':
                pr = 0.5
            elif self.size == '13x18':
                pr = 1
            elif self.size == '15x21':
                pr = 1.5
            elif self.size == '20x25':
                pr = 4
            elif self.size == 'A4':
                pr = 6
            elif self.size == 'A3':
                pr = 10
            elif self.size == '50x60':
                pr = 20
            elif self.size == '100x50':
                pr = 35
            elif self.size == '100x70':
                pr = 45
            elif self.size == '160x60':
                pr = 60
            elif self.size == '140x100':
                pr = 90
            elif self.size == '118 1mb':
                pr = 40

            if self.is_gloss and self.is_color:
                pr = pr*1.2
            elif not self.is_gloss and not self.is_color:
                pr = pr*0.8
            elif self.is_gloss and not self.is_color:
                pr = pr*0.96

            pr = pr*self.quantity
            self.price = pr
            self.save()


class Address(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.CharField(max_length=255)
    city = models.CharField(max_length=40)
    street = models.CharField(max_length=60)
    home_number = models.CharField(max_length=8)
    postal_code = models.CharField(max_length=6)
    telephone_number = models.CharField(max_length=12)
    user = models.OneToOneField(
        User, on_delete=models.SET_NULL, blank=True, null=True)


class Order(models.Model):
    date = models.DateTimeField(auto_now=True)
    payment_method = models.CharField(
        max_length=30,
        choices=PAYMENT_CHOICS,
        default='przelew'
    )
    delivery_method = models.CharField(
        max_length=30,
        choices=DELIVERY_CHOICES,
        default='poczta'
    )
    is_paid = models.BooleanField(default=False)
    cost = models.DecimalField(max_digits=9, decimal_places=2, blank=True)
    printout = models.OneToOneField(Printout, on_delete=models.CASCADE)
    address = models.OneToOneField(Address, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.cost == 0:
            if self.delivery_method == 'poczta':
                deliveryCost = 6.70
            elif self.delivery_method == 'kurier':
                deliveryCost = 10.90
            elif self.delivery_method == 'paczkomat':
                deliveryCost = 8.99

            totalCost = self.printout.price + Decimal(deliveryCost)
            self.cost = totalCost
            self.save()

myproject/register/models.py
from django.db import models

# Create your models here.

myproject/register/forms.py
from cProfile import label
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from httpx import Auth
from requests import request
from print4you.models import Address


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]
        labels = {
            'username': ('Nazwa użytkownika'),
            'email': ('Adres e-mail'),
            'first_name': ('Imię'),
            'last_name': ('Nazwisko'),
    }

class SetAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ["first_name", "last_name", "email", "city", "street", "home_number", "postal_code", "telephone_number", "user"]
        labels = {
            'first_name': ('Imię'),
            'last_name': ('Nazwisko'),
            'email': ('Adres e-mail'),
            'city': ('Miasto'),
            'street': ('Ulica'),
            'home_number': ('Numer domu'),
            'postal_code': ('Kod pocztowy'),
            'telephone_number': ('Numer telefonu'),
            }
        widgets = {'user': forms.HiddenInput()}

class EditAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ["first_name", "last_name", "email", "city", "street", "home_number", "postal_code", "telephone_number", "user"]
        labels = {
            'first_name': ('Imię'),
            'last_name': ('Nazwisko'),
            'email': ('Adres e-mail'),
            'city': ('Miasto'),
            'street': ('Ulica'),
            'home_number': ('Numer domu'),
            'postal_code': ('Kod pocztowy'),
            'telephone_number': ('Numer telefonu'),
            }
        widgets = {'user': forms.HiddenInput()}

myproject/register/views.py
# views.py
from django.contrib.auth import login, authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from register.forms import EditAddressForm
from register.forms import SetAddressForm
from register.forms import EditProfileForm
from register.forms import RegisterForm
from django.views import generic
from django.urls import reverse_lazy
from print4you.models import User


# Create your views here.

def homepage(request):
    return render(request, "homepage.html")


def about(request):
    return render(request, "about.html")


def homepage_redirect(request):
    return redirect("homepage")


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Pomyślnie utworzono konto. Możesz się teraz zalogować.')
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request, "register.html", {"form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(
                    request, f"Jesteś zalogowany jako {username}.")
                return redirect("homepage")
            else:
                messages.error(
                    request, "Niewłaściwa nazwa użytkownika lub hasło.")
        else:
            messages.error(request, "Niewłaściwa nazwa użytkownika lub hasło.")
    form = AuthenticationForm()
    return render(request, "login.html", {"form": form})


class UserEditView(generic.UpdateView):
    form_class = EditProfileForm
    template_name = 'registration/edit_profile.html'
    success_url = reverse_lazy('profile')

    def get_object(self):
        if self.request.method == "POST":
            messages.add_message(self.request, messages.INFO,
                                 'Zapisano dane osobiste.')
        return self.request.user


def add_address(request):

    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.id)

    form = SetAddressForm(initial={"user": user})

    if request.method == 'POST':
        form = SetAddressForm(request.POST)
        messages.info(request, 'Zapisano dane adresu.')
        if form.is_valid():
            form.save()
        return redirect("profile")

    context = {'form': form}
    return render(request, 'registration/set_address.html', context)


class AddressEditView(generic.UpdateView):

    form_class = EditAddressForm
    template_name = 'registration/edit_address.html'
    success_url = reverse_lazy('profile')

    def get_object(self):
        if self.request.method == "POST":
            messages.add_message(
                self.request, messages.INFO, 'Zapisano dane adresu.')
        return self.request.user.address


def address_redirect(request):
    try:
        if request.user.address is not None:
            response = redirect('/edit_address/')
            return response
    except:
        response = redirect('/set_address/')
        return response

myproject/templates/Calculator-template.html
<!DOCTYPE html>
<html lang="pl">

<head>
 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/f394a4746b.js" crossorigin="anonymous"></script>
  <title>Print4You</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/calculator-style.css' %}">
  
</head>

<body data-bs-spy="scroll" data-bs-target="#navbar" data-bs-offset="82">
  <nav id="navbar" class=" navbar navbar-expand-lg position-fixed top-0 w-100 py-3">
    <div class="container">
      <a class="navbar-brand white-text" href="#"><i class="fa-solid fa-print"></i>Print<span class="mint-text">4You</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href={% url "homepage" %}>Home</a>
          <a class="nav-link" href={% url "homepage" %}>o nas</a>
          <a class="nav-link" href={% url "offer" %}>oferta</a>
          <a class="nav-link" href={% url "calculator" %}>zamów</a>
          </div>
          <div class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
          <a class="nav-link login-btn" href={% url "profile" %}>profil</a>
          <a class="nav-link login-btn" href={% url "logout" %}>wyloguj</a>
          {% else %}
          <a class="nav-link login-btn" href={% url "login" %}>zaloguj</a>
          <a class="nav-link signin-btn" href={% url "register" %}>rejestracja</a>
          {% endif %}
          </div>
        
      </div>
    </div>
  </nav>
<main>
  <div class="content">
    {% for msg in messages %}
      {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
        <div class="alert alert-success" role="alert" style="text-align: center">
          {{ msg }}
        </div> 
      {% elif msg.level == DEFAULT_MESSAGE_LEVELS.INFO %} 
        <div class="alert alert-info" role="alert" style="text-align: center">
          {{ msg }}
        </div> 
      {% elif msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %} 
        <div class="alert alert-danger" role="alert" style="text-align: center">
          {{ msg }}
        </div> 
      {% endif %}
	  {% endfor %}
    <div class="centering">
      
{% block title %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
</div>

</main>
<footer class="footer">
    <div class="container py-3">
      <div class="row">
        <div class="col-4 link"><a href="#">oferta</a></div>
        <div class="col-4 link"><a href="#">o nas</a></div>
        <div class="col-4 link"><a href="mailto:print4u.team@gmail.com">kontakt</a></div>
       <div class="col-12 company-name">Print4You@2022</div>
       
    </div>
  </footer>     
  

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
crossorigin="anonymous"></script>
</body>

</html>

myproject/templates/Template.html
<!DOCTYPE html>
<html lang="pl">

<head>
 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/f394a4746b.js" crossorigin="anonymous"></script>
  <title>Print4You</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/template-style.css' %}">
  
</head>

<body data-bs-spy="scroll" data-bs-target="#navbar" data-bs-offset="82">
  <nav id="navbar" class=" navbar navbar-expand-lg position-fixed top-0 w-100 py-3">
    <div class="container">
      <a class="navbar-brand white-text" href="#"><i class="fa-solid fa-print"></i>Print<span class="mint-text">4You</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href={% url "homepage" %}>Home</a>
          <a class="nav-link" href={% url "about" %}>o nas</a>
          <a class="nav-link" href={% url "offer" %}>oferta</a>
          <a class="nav-link" href={% url "calculator" %}>zamów</a>
          </div>
          <div class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
          <a class="nav-link login-btn" href={% url "profile" %}>profil</a>
          <a class="nav-link login-btn" href={% url "logout" %}>wyloguj</a>
          {% else %}
          <a class="nav-link login-btn" href={% url "login" %}>zaloguj</a>
          <a class="nav-link signin-btn" href={% url "register" %}>rejestracja</a>
          {% endif %}
          </div>
        
      </div>
    </div>
  </nav>
<main>
  <div class="content">
    {% for msg in messages %}
      {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
        <div class="alert alert-success" role="alert" style="text-align: center">
          {{ msg }}
        </div> 
      {% elif msg.level == DEFAULT_MESSAGE_LEVELS.INFO %} 
        <div class="alert alert-info" role="alert" style="text-align: center">
          {{ msg }}
        </div> 
      {% elif msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %} 
        <div class="alert alert-danger" role="alert" style="text-align: center">
          {{ msg }}
        </div> 
      {% endif %}
	  {% endfor %}
    <div class="centering">
      
      {% block title %}
      
      {% endblock %}
      
      
      {% block content %}
      <div class="block-calculator">
          <div class="container cont ">
              <div class="row">
                  <div class="left-side col-6">
                      <p>
                      <table>
                          <form action="" method="POST" enctype="multipart/form-data">
                              {% csrf_token %}
                              {{ form.as_table }}
                      </table>
                      </p>
      
                      <p>
                          <button class="btn-calc" type="submit">Oblicz cenę</button>
                      </p>
                  </div>
                  {% if printout %}
      
                  <div class="right-side col-6">
      
                      {% if printout.is_color %}
                          {% if printout.is_gloss %}
                          <img src="{{ imagePath }}" class="user-photo glossy" />
                          {% else %}
                          <img src="{{ imagePath }}" class="user-photo non-glossy" />
                          {% endif %}
                      {% else %}
                          {% if printout.is_gloss %}
                          <img src="{{ imagePath }}" class="user-photo grayscale glossy" />
                          {% else %}
                          <img src="{{ imagePath }}" class="user-photo grayscale-non-glossy" />
                          {% endif %}
                      {% endif %}
      
                      <p class="price">
                          {{ price }}
                      </p>
                      <p>
                          <a class="btn-calc" href="{% url 'new_order' pk=printout.id %}">Zamów</a>
                      </p>
                  </div>
              </div>
              {% endif %}
          </div>
      </div>
      {% endblock %}
</div>
</div>

</main>
<footer class="footer">
    <div class="container py-3">
      <div class="row">
        <div class="col-4 link"><a href="#">oferta</a></div>
        <div class="col-4 link"><a href="#">o nas</a></div>
        <div class="col-4 link"><a href="mailto:print4u.team@gmail.com">kontakt</a></div>
       <div class="col-12 company-name">Print4You@2022</div>
       
    </div>
  </footer>     
  

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
crossorigin="anonymous"></script>
</body>

</html>

myproject/templates/calculator.html
{% extends 'calculator-template.html' %}
{% block title %}
<h1>Kalkulator</h1>
{% endblock %}


{% block content %}
<div class="block-calculator">
    <div class="container cont ">
        <div class="row">
            <div class="left-side col-12 col-lg-6">
                <p>
                <table>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_table }}
                </table>
                </p>

                <p>
                    <button class="btn-calc" type="submit">Oblicz cenę</button>
                </p>
            </div>
            {% if printout %}

            <div class="right-side col-12 col-lg-6">

                {% if printout.is_color %}
                    {% if printout.is_gloss %}
                    <img src="{{ imagePath }}" class="user-photo glossy" />
                    {% else %}
                    <img src="{{ imagePath }}" class="user-photo non-glossy" />
                    {% endif %}
                {% else %}
                    {% if printout.is_gloss %}
                    <img src="{{ imagePath }}" class="user-photo grayscale glossy" />
                    {% else %}
                    <img src="{{ imagePath }}" class="user-photo grayscale-non-glossy" />
                    {% endif %}
                {% endif %}

                <p class="price">
                    {{ price }}
                </p>
                <p>
                    <a class="btn-calc" href="{% url 'new_order' pk=printout.id %}">Zamów</a>
                </p>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<style>
    .container
    {
        width:100%;
    }
    #id_image_file
      {
          display:block;
      }

    .left-side
    {
        overflow: hidden;
    }
    .right-side {
        
        text-align: center;
    }

    .right-side img {

        max-width: 500px;
    }

    h1 {
        font-size: 30px;
        font-weight: bold;
    }

    .cont {
       
        font-size: 20px;
        font-weight: bold;
    }

    .price {
        font-size: 25px;
    }

    .btn-calc {
        text-decoration: none;
        background-color: #fabb0c;
        padding: 10px;
        color: black;
        transition: color 0.2s;
        border: none;
        font-weight: bold;
    }

    .btn-calc:hover {
        color: #3eb489;
    }

    #id_quantity {
        width: 50px;
    }

    label {
        width: 150px;
        padding-bottom: 12px;
    }

    .img-link {
        background: red;
    }

    .glossy {
        box-shadow: 0px 0px 20px #fff;
    }

    .non-glossy{
        filter: contrast(70%);
    }

    .grayscale{
        filter: grayscale(1);
    }

    .grayscale-non-glossy{
        filter: grayscale(1) contrast(70%);
    }
    *
    {
        max-width: 100%;
    }
    @media(max-width:500px)
    {
        .right-side
        {
            max-width: 300px;
            margin:auto;
        }
        .left-side
        {
            max-width: 300px;
            
        }
      
      #id_image_file
      {
          width:100px;
          font-size: 15px;
      }
        .right-side img {
        max-width: 100%;
        
    }
    .row
    {
        margin:auto;
        padding: 10px;
    }
    }
    @media(min-width:1000px)
    {
       .left-side
       {
        padding-right:30px;
       }
       .right-side
       {
           padding-left: 30px;
       }
       
    }
   
</style>
{% endblock %}

myproject/templates/change_password.html
{% extends 'Template.html' %}
{% load crispy_forms_tags %}

{% block title %}<h1>Zmień hasło</h1>{% endblock title %}

{% block content %} 
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'edit_profile' %}">Powrót</a>
        <button type="submit" class="btn btn-success" style="float:right">Zmień hasło</button>
    </form>


    <style>
    .btn-success
	{
		background-color: #fabb0c;
		color:black;
	}
    </style>
{% endblock content %}

myproject/templates/login.html
{% extends 'template.html' %}
{% load static %}

		{% block title %}
		{% if user.is_authenticated %}
		<h1>Jesteś już zalogowany!</h1>
		<p>Możesz sprawdzić swoje konto <a href="{% url "profile" %}">tutaj!</a></p>
		{% else %}
		<h1>Zaloguj się <i class="fa-solid fa-right-to-bracket"></i></h1>
		{% endif %}
		{% endblock %}
			
		{% load crispy_forms_tags %}
			
		{% block content %}
		{% if not user.is_authenticated %}
		<form method="post" class="login-form">
		{% csrf_token %}
		{{form|crispy}}
		<p>Nie masz konta? Stwórz je <a href="{% url "register" %}">tutaj</a></p>
		<p></p><a href="{% url "password_reset" %}">Zapomniałeś hasło?</a></p>
		<button type="submit" class="btn btn-success" ">Zaloguj</button>	
		</form>
		{% endif %}
		
<style>
	.login-form
	{
		font-weight: bold;
		font-size: 20px;
		
	}
	h1
	{
		font-size: 30px;
		font-weight: bold;
	}
	.btn-success
	{
		background-color: #fabb0c;
		color:black;
	}
</style>
		
			{% endblock %}

myproject/templates/order.html
{% extends 'template.html' %}
{% block title %}
<h1>Zamówienie</h1>
{% endblock %}


{% block content %}
<p>
    <table>
        <form action="" method="POST">
            {% csrf_token %}
            {{ orderForm.as_table }}
            {{ addressForm.as_table }}
    </table>
</p>
<p>
    <button type="submit" class="btn btn-success">Przejdź do płatności</button>
</p>
{% endblock %}

myproject/templates/payment.html
{% extends 'template.html' %}
{% load static %}

{% block title %}

<p class="title"> Opłać zamówienie</p>
{% endblock %}


{% block content %}

<p>
    <table>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <p>
                Data: {{ order.date }} <br>
                Metoda płatności: {{ order.payment_method }} <br>
                Należność: {{ order.cost }}
            </p>
            <p>
                <button type="submit">Opłać zamówienie</button>
            </p>
    </table>
</p>


<style>
    .title
	{
		font-size: 30px;
		font-weight: bold;
	}
</style>

{% endblock %}

myproject/templates/profile.html
{% extends 'template.html' %}
{% block title %}
<h1>Twój profil</h1>
{% endblock %}
{% for msg in messages %}
	<div class="alert alert-success" role="alert" style="text-align: center">
	    {{ msg }}
    </div>
{% endfor %}

{% block content %}
<p>
    Witaj {{ user }}
</p>
<p>
    <button class="btn btn-success" onclick="window.location.href='/address_redirect/'">Edytuj adres</button>
</p>
<p>
    <button class="btn btn-success" onclick="window.location.href='/edit_profile/'">Edytuj dane osobowe</button>
</p>
<style>
    .btn-success
	{
		background-color: #fabb0c;
		color:black;
	}
</style>
{% endblock %}